/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-04-21 14:19:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.store.model.User;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1745244128518L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.store.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Inter', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar {\r\n");
      out.write("        background-color: #f5ede3;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        padding: 12px 40px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo {\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        color: #4b2e2e;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .center-nav {\r\n");
      out.write("        flex-grow: 1;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .center-links {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .center-links li a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #2f2f2f;\r\n");
      out.write("        font-size: 17px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        padding-bottom: 5px;\r\n");
      out.write("        transition: color 0.3s ease, border-bottom 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .center-links li a:hover {\r\n");
      out.write("        color: #a15c38;\r\n");
      out.write("        border-bottom: 2px solid #a15c38;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .center-links li a.active {\r\n");
      out.write("        color: #9c4f1c;\r\n");
      out.write("        border-bottom: 2px solid #9c4f1c;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .auth-links {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 12px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .auth-btn {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        background-color: #decab5;\r\n");
      out.write("        padding: 8px 16px;\r\n");
      out.write("        color: #2f2f2f;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("        transition: background-color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .auth-btn:hover {\r\n");
      out.write("        background-color: #c8b099;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<header class=\"navbar\">\r\n");
      out.write("    <h1 class=\"logo\">Tune Cart</h1>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"center-nav\">\r\n");
      out.write("        <ul class=\"nav-links center-links\">\r\n");
      out.write("            <li><a href=\"home\" class=\"");
      out.print( request.getRequestURI().endsWith("home") ? "active" : "" );
      out.write("\">Home</a></li>\r\n");
      out.write("            <li><a href=\"cart.jsp\" class=\"");
      out.print( request.getRequestURI().endsWith("cart.jsp") ? "active" : "" );
      out.write("\">Cart</a></li>\r\n");
      out.write("            <li><a href=\"orders.jsp\" class=\"");
      out.print( request.getRequestURI().endsWith("orders.jsp") ? "active" : "" );
      out.write("\">Orders</a></li>\r\n");
      out.write("            <li><a href=\"about.jsp\" class=\"");
      out.print( request.getRequestURI().endsWith("about.jsp") ? "active" : "" );
      out.write("\">About Us</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"auth-links\">\r\n");
      out.write("        ");

            // Check if the user is logged in
            User user = (User) session.getAttribute("user");
            if (user != null) {
        
      out.write("\r\n");
      out.write("            <!-- Display user profile if logged in -->\r\n");
      out.write("            <div style=\"display: flex; align-items: center; gap: 10px;\">\r\n");
      out.write("			<img src=\" >\" alt=\"Profile\" style=\"width: 30px; height: 30px; border-radius: 50%;\">\r\n");
      out.write("                \r\n");
      out.write("                <span style=\"font-weight: 600; color: #2f2f2f;\">");
      out.print( user.getFullName() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");

            } else {
        
      out.write("\r\n");
      out.write("            <!-- Show Login and Register button if user is not logged in -->\r\n");
      out.write("            <a href=\"login\" class=\"auth-btn\">Login</a>\r\n");
      out.write("            <a href=\"register\" class=\"auth-btn\">Register</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <title>Register</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"styles.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\"\r\n");
      out.write("        href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" />\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      font-family: Arial, sans-serif;\r\n");
      out.write("      background-color: #efcdb8;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    main {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      min-height: calc(100vh - 70px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .register-box {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      padding: 30px 40px;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      width: 450px;\r\n");
      out.write("      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .register-box h2 {\r\n");
      out.write("      background-color: #40362e;\r\n");
      out.write("      color: white;\r\n");
      out.write("      margin: -30px -40px 20px -40px;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-size: 24px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    label {\r\n");
      out.write("      display: block;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      margin-top: 15px;\r\n");
      out.write("      text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"text\"],\r\n");
      out.write("    input[type=\"email\"],\r\n");
      out.write("    input[type=\"password\"] {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      margin-top: 5px;\r\n");
      out.write("      border: 1px solid #ddd;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      background-color: #f7f7f7;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .register-btn {\r\n");
      out.write("      background-color: #40362e;\r\n");
      out.write("      color: white;\r\n");
      out.write("      border: none;\r\n");
      out.write("      padding: 12px 24px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      border-radius: 25px;\r\n");
      out.write("      margin-top: 20px;\r\n");
      out.write("      transition: background-color 0.3s ease, transform 0.2s ease;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .register-btn:hover {\r\n");
      out.write("      background-color: #2f2a20;\r\n");
      out.write("      transform: scale(1.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .register-link {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin-top: 15px;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .register-link a {\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      color: black;\r\n");
      out.write("      text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .message {\r\n");
      out.write("      color: green;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin-top: 15px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("  <div class=\"register-box\">\r\n");
      out.write("    <h2>Register</h2>\r\n");
      out.write("    <form action=\"register\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("      <label for=\"name\">Full Name</label>\r\n");
      out.write("      <input type=\"text\" id=\"name\" name=\"name\" required />\r\n");
      out.write("\r\n");
      out.write("      <label for=\"email\">Email</label>\r\n");
      out.write("      <input type=\"email\" id=\"email\" name=\"email\" required />\r\n");
      out.write("      \r\n");
      out.write("       <label for=\"address\">Address</label>\r\n");
      out.write("      <input type=\"text\" id=\"address\" name=\"address\" />\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <label for=\"phone\">Phone Number</label>\r\n");
      out.write("      <input type=\"text\" id=\"phone\" name=\"phone\" />\r\n");
      out.write("      \r\n");
      out.write("      <label for=\"password\">Password</label>\r\n");
      out.write("      <input type=\"password\" id=\"password\" name=\"password\" required />\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      <button type=\"submit\" class=\"register-btn\">Register</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"register-link\">\r\n");
      out.write("      <p>Already have an account? <a href=\"login.jsp\">Login</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");

      String message = request.getParameter("message");
      if (message != null) {
    
      out.write("\r\n");
      out.write("    <div class=\"message\">");
      out.print( message );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
